### ISSUE TITLE
Universal env variables

### ISSUE THREAD

**Issue by mcagalj** [tonijukica/thesis-app#34]
Mozda mozemo koristiti cross-env paket da izbjegnemo postavljanje env varijabli posebno za razne OS-ove [(cros-env)](https://www.npmjs.com/package/cross-env).

https://github.com/tonijukica/thesis-app/blob/7bf6d3b2339f16314b735cc6ed7d63e94ce25f33/package.json#L9

**Comment by tonijukica** [comment]
Odlicno rjesenje, implementirano u 722212519cf55ae4b2349620e8f6284aed961a19.
